package it.polito.ma.g14.timebank.utils

import it.polito.ma.g14.timebank.fragments.SkillEntry

class SkillList {

    var skill_list : MutableList<SkillEntry> = mutableListOf(
        SkillEntry("Accountant", false),
        SkillEntry("Accounts Assistant", false),
        SkillEntry("Accounts Clerk", false),
        SkillEntry("Accounts Manager", false),
        SkillEntry("Accounts Staff", false),
        SkillEntry("Acoustic Engineer", false),
        SkillEntry("Actor", false),
        SkillEntry("Actress", false),
        SkillEntry("Actuary", false),
        SkillEntry("Acupuncturist", false),
        SkillEntry("Adjustor", false),
        SkillEntry("Administration Assistant", false),
        SkillEntry("Administration Clerk", false),
        SkillEntry("Administration Manager", false),
        SkillEntry("Administration Staff", false),
        SkillEntry("Administrator", false),
        SkillEntry("Advertising Agent", false),
        SkillEntry("Advertising Assistant", false),
        SkillEntry("Advertising Clerk", false),
        SkillEntry("Advertising Contractor", false),
        SkillEntry("Advertising Executive", false),
        SkillEntry("Advertising Manager", false),
        SkillEntry("Advertising Staff", false),
        SkillEntry("Aerial Erector", false),
        SkillEntry("Aerobic Instructor", false),
        SkillEntry("Aeronautical Engineer", false),
        SkillEntry("Agent", false),
        SkillEntry("Air Traffic Controller", false),
        SkillEntry("Aircraft Designer", false),
        SkillEntry("Aircraft Engineer", false),
        SkillEntry("Aircraft Maintenance Engineer", false),
        SkillEntry("Aircraft Surface Finisher", false),
        SkillEntry("Airman", false),
        SkillEntry("Airport Controller", false),
        SkillEntry("Airport Manager", false),
        SkillEntry("Almoner", false),
        SkillEntry("Ambulance Controller", false),
        SkillEntry("Ambulance Crew", false),
        SkillEntry("Ambulance Driver", false),
        SkillEntry("Amusement Arcade Worker", false),
        SkillEntry("Anaesthetist", false),
        SkillEntry("Analyst", false),
        SkillEntry("Analytical Chemist", false),
        SkillEntry("Animal Breeder", false),
        SkillEntry("Anthropologist", false),
        SkillEntry("Antique Dealer", false),
        SkillEntry("Applications Engineer", false),
        SkillEntry("Applications Programmer", false),
        SkillEntry("Arbitrator", false),
        SkillEntry("Arborist", false),
        SkillEntry("Archaeologist", false),
        SkillEntry("Architect", false),
        SkillEntry("Archivist", false),
        SkillEntry("Area Manager", false),
        SkillEntry("Armourer", false),
        SkillEntry("Aromatherapist", false),
        SkillEntry("Art Critic", false),
        SkillEntry("Art Dealer", false),
        SkillEntry("Art Historian", false),
        SkillEntry("Art Restorer", false),
        SkillEntry("Artexer", false),
        SkillEntry("Artist", false),
        SkillEntry("Arts", false),
        SkillEntry("Assembly Worker", false),
        SkillEntry("Assessor", false),
        SkillEntry("Assistant", false),
        SkillEntry("Assistant Caretaker", false),
        SkillEntry("Assistant Cook", false),
        SkillEntry("Assistant Manager", false),
        SkillEntry("Assistant Nurse", false),
        SkillEntry("Assistant Teacher", false),
        SkillEntry("Astrologer", false),
        SkillEntry("Astronomer", false),
        SkillEntry("Attendant", false),
        SkillEntry("Au Pair", false),
        SkillEntry("Auction Worker", false),
        SkillEntry("Auctioneer", false),
        SkillEntry("Audiologist", false),
        SkillEntry("Audit Clerk", false),
        SkillEntry("Audit Manager", false),
        SkillEntry("Auditor", false),
        SkillEntry("Auto Electrician", false),
        SkillEntry("Auxiliary Nurse", false),
        SkillEntry("Bacon Curer", false),
        SkillEntry("Baggage Handler", false),
        SkillEntry("Bailiff", false),
        SkillEntry("Baker", false),
        SkillEntry("Bakery Assistant", false),
        SkillEntry("Bakery Manager", false),
        SkillEntry("Bakery Operator", false),
        SkillEntry("Balloonist", false),
        SkillEntry("Bank Clerk", false),
        SkillEntry("Bank Manager", false),
        SkillEntry("Bank Messenger", false),
        SkillEntry("Baptist Minister", false),
        SkillEntry("Bar Manager", false),
        SkillEntry("Bar Steward", false),
        SkillEntry("Barber", false),
        SkillEntry("Barmaid", false),
        SkillEntry("Barman", false),
        SkillEntry("Barrister", false),
        SkillEntry("Beautician", false),
        SkillEntry("Beauty Therapist", false),
        SkillEntry("Betting Shop", false),
        SkillEntry("Bill Poster", false),
        SkillEntry("Bingo Caller", false),
        SkillEntry("Biochemist", false),
        SkillEntry("Biologist", false),
        SkillEntry("Blacksmith", false),
        SkillEntry("Blind Assembler", false),
        SkillEntry("Blind Fitter", false),
        SkillEntry("Blinds Installer", false),
        SkillEntry("Boat Builder", false),
        SkillEntry("Body Fitter", false),
        SkillEntry("Bodyguard", false),
        SkillEntry("Bodyshop", false),
        SkillEntry("Book Binder", false),
        SkillEntry("Book Seller", false),
        SkillEntry("Book-Keeper", false),
        SkillEntry("Booking Agent", false),
        SkillEntry("Booking Clerk", false),
        SkillEntry("Bookmaker", false),
        SkillEntry("Botanist", false),
        SkillEntry("Branch Manager", false),
        SkillEntry("Breeder", false),
        SkillEntry("Brewer", false),
        SkillEntry("Brewery Manager", false),
        SkillEntry("Brewery Worker", false),
        SkillEntry("Bricklayer", false),
        SkillEntry("Broadcaster", false),
        SkillEntry("Builder", false),
        SkillEntry("Builders Labourer", false),
        SkillEntry("Building Advisor", false),
        SkillEntry("Building Control", false),
        SkillEntry("Building Engineer", false),
        SkillEntry("Building Estimator", false),
        SkillEntry("Building Foreman", false),
        SkillEntry("Building Inspector", false),
        SkillEntry("Building Manager", false),
        SkillEntry("Building Surveyor", false),
        SkillEntry("Bursar", false),
        SkillEntry("Bus Company", false),
        SkillEntry("Bus Conductor", false),
        SkillEntry("Bus Driver", false),
        SkillEntry("Bus Mechanic", false),
        SkillEntry("Bus Valeter", false),
        SkillEntry("Business Consultant", false),
        SkillEntry("Business Proprietor", false),
        SkillEntry("Butcher", false),
        SkillEntry("Butchery Manager", false),
        SkillEntry("Butler", false),
        SkillEntry("Buyer", false),
        SkillEntry("Cab Driver", false),
        SkillEntry("Cabinet Maker", false),
        SkillEntry("Cable Contractor", false),
        SkillEntry("Cable Jointer", false),
        SkillEntry("Cable TV Installer", false),
        SkillEntry("Cafe Owner", false),
        SkillEntry("Cafe Staff", false),
        SkillEntry("Cafe Worker", false),
        SkillEntry("Calibration Manager", false),
        SkillEntry("Camera Repairer", false),
        SkillEntry("Cameraman", false),
        SkillEntry("Car Dealer", false),
        SkillEntry("Car Delivery Driver", false),
        SkillEntry("Car Park Attendant", false),
        SkillEntry("Car Salesman", false),
        SkillEntry("Car Valet", false),
        SkillEntry("Car Wash Attendant", false),
        SkillEntry("Care Assistant", false),
        SkillEntry("Care Manager", false),
        SkillEntry("Careers Advisor", false),
        SkillEntry("Careers Officer", false),
        SkillEntry("Caretaker", false),
        SkillEntry("Cargo Operator", false),
        SkillEntry("Carpenter", false),
        SkillEntry("Carpet Cleaner", false),
        SkillEntry("Carpet Fitter", false),
        SkillEntry("Carpet Retailer", false),
        SkillEntry("Carphone Fitter", false),
        SkillEntry("Cartographer", false),
        SkillEntry("Cartoonist", false),
        SkillEntry("Cashier", false),
        SkillEntry("Casual Worker", false),
        SkillEntry("Caterer", false),
        SkillEntry("Catering Consultant", false),
        SkillEntry("Catering Manager", false),
        SkillEntry("Catering Staff", false),
        SkillEntry("Caulker", false),
        SkillEntry("Ceiling Contractor", false),
        SkillEntry("Ceiling Fixer", false),
        SkillEntry("Cellarman", false),
        SkillEntry("Chambermaid", false),
        SkillEntry("Chandler", false),
        SkillEntry("Chaplain", false),
        SkillEntry("Charge Hand", false),
        SkillEntry("Charity Worker", false),
        SkillEntry("Chartered", false),
        SkillEntry("Chartered Accountant", false),
        SkillEntry("Chauffeur", false),
        SkillEntry("Chef", false),
        SkillEntry("Chemist", false),
        SkillEntry("Chicken Chaser", false),
        SkillEntry("Child Minder", false),
        SkillEntry("Childminder", false),
        SkillEntry("Chimney Sweep", false),
        SkillEntry("China Restorer", false),
        SkillEntry("Chiropodist", false),
        SkillEntry("Chiropractor", false),
        SkillEntry("Choreographer", false),
        SkillEntry("Church Officer", false),
        SkillEntry("Church Warden", false),
        SkillEntry("Cinema Manager", false),
        SkillEntry("Circus Proprietor", false),
        SkillEntry("Circus Worker", false),
        SkillEntry("Civil Engineer", false),
        SkillEntry("Civil Servant", false),
        SkillEntry("Claims Adjustor", false),
        SkillEntry("Claims Assessor", false),
        SkillEntry("Claims Manager", false),
        SkillEntry("Clairvoyant", false),
        SkillEntry("Classroom Aide", false),
        SkillEntry("Cleaner", false),
        SkillEntry("Clergyman", false),
        SkillEntry("Cleric", false),
        SkillEntry("Clerk", false),
        SkillEntry("Commissioned", false),
        SkillEntry("Consultant", false),
        SkillEntry("Coroner", false),
        SkillEntry("Councillor", false),
        SkillEntry("Counsellor", false),
        SkillEntry("Dealer", false),
        SkillEntry("Decorator", false),
        SkillEntry("Delivery Driver", false),
        SkillEntry("Doctor", false),
        SkillEntry("Driver", false),
        SkillEntry("Economist", false),
        SkillEntry("Editor", false),
        SkillEntry("Employee", false),
        SkillEntry("Employment", false),
        SkillEntry("Engineer", false),
        SkillEntry("English Teacher", false),
        SkillEntry("Entertainer", false),
        SkillEntry("Envoy", false),
        SkillEntry("Executive", false),
        SkillEntry("Farmer", false),
        SkillEntry("Fireman", false),
        SkillEntry("Floor Layer", false),
        SkillEntry("Floor Manager", false),
        SkillEntry("Florist", false),
        SkillEntry("Flour Miller", false),
        SkillEntry("Flower Arranger", false),
        SkillEntry("Flying Instructor", false),
        SkillEntry("Foam Convertor", false),
        SkillEntry("Food Processor", false),
        SkillEntry("Footballer", false),
        SkillEntry("Foreman", false),
        SkillEntry("Forensic Scientist", false),
        SkillEntry("Forest Ranger", false),
        SkillEntry("Forester", false),
        SkillEntry("Fork Lift Truck Driver", false),
        SkillEntry("Forwarding Agent", false),
        SkillEntry("Foster Parent", false),
        SkillEntry("Foundry Worker", false),
        SkillEntry("Fraud Investigator", false),
        SkillEntry("French Polisher", false),
        SkillEntry("Fruiterer", false),
        SkillEntry("Fuel Merchant", false),
        SkillEntry("Fund Raiser", false),
        SkillEntry("Funeral Director", false),
        SkillEntry("Funeral Furnisher", false),
        SkillEntry("Furnace Man", false),
        SkillEntry("Furniture Dealer", false),
        SkillEntry("Furniture Remover", false),
        SkillEntry("Furniture Restorer", false),
        SkillEntry("Furrier", false),
        SkillEntry("Gallery Owner", false),
        SkillEntry("Gambler", false),
        SkillEntry("Gamekeeper", false),
        SkillEntry("Gaming Board Inspector", false),
        SkillEntry("Gaming Club Manager", false),
        SkillEntry("Gaming Club Proprietor", false),
        SkillEntry("Garage Attendant", false),
        SkillEntry("Garage Foreman", false),
        SkillEntry("Garage Manager", false),
        SkillEntry("Garda", false),
        SkillEntry("Garden Designer", false),
        SkillEntry("Gardener", false),
        SkillEntry("Gas Fitter", false),
        SkillEntry("Gas Mechanic", false),
        SkillEntry("Gas Technician", false),
        SkillEntry("Gate Keeper", false),
        SkillEntry("Genealogist", false),
        SkillEntry("General Practitioner", false),
        SkillEntry("Geologist", false),
        SkillEntry("Geophysicist", false),
        SkillEntry("Gilder", false),
        SkillEntry("Glass Worker", false),
        SkillEntry("Glazier", false),
        SkillEntry("Goldsmith", false),
        SkillEntry("Golf Caddy", false),
        SkillEntry("Golf Club Professional", false),
        SkillEntry("Golfer", false),
        SkillEntry("Goods Handler", false),
        SkillEntry("Governor", false),
        SkillEntry("Granite Technician", false),
        SkillEntry("Graphic Designer", false),
        SkillEntry("Graphologist", false),
        SkillEntry("Grave Digger", false),
        SkillEntry("Gravel Merchant", false),
        SkillEntry("Green Keeper", false),
        SkillEntry("Greengrocer", false),
        SkillEntry("Grocer", false),
        SkillEntry("Groom", false),
        SkillEntry("Ground Worker", false),
        SkillEntry("Groundsman", false),
        SkillEntry("Guest House Owner", false),
        SkillEntry("Guest House Proprietor", false),
        SkillEntry("Gun Smith", false),
        SkillEntry("Gynaecologist", false),
        SkillEntry("HGV Driver", false),
        SkillEntry("HGV Mechanic", false),
        SkillEntry("Hairdresser", false),
        SkillEntry("Handyman", false),
        SkillEntry("Hardware Dealer", false),
        SkillEntry("Haulage Contractor", false),
        SkillEntry("Hawker", false),
        SkillEntry("Health Advisor", false),
        SkillEntry("Health And Safety", false),
        SkillEntry("Health Care Assistant", false),
        SkillEntry("Health Consultant", false),
        SkillEntry("Health Nurse", false),
        SkillEntry("Health Planner", false),
        SkillEntry("Health Service", false),
        SkillEntry("Health Therapist", false),
        SkillEntry("Health Visitor", false),
        SkillEntry("Hearing Therapist", false),
        SkillEntry("Heating Engineer", false),
        SkillEntry("Herbalist", false),
        SkillEntry("Highway Inspector", false),
        SkillEntry("Hire Car Driver", false),
        SkillEntry("Historian", false),
        SkillEntry("History Teacher", false),
        SkillEntry("Hod Carrier", false),
        SkillEntry("Home Economist", false),
        SkillEntry("Home Help", false),
        SkillEntry("Homecare Manager", false),
        SkillEntry("Homeopath", false),
        SkillEntry("Homeworker", false),
        SkillEntry("Hop Merchant", false),
        SkillEntry("Horse Breeder", false),
        SkillEntry("Horse Dealer", false),
        SkillEntry("Horse Riding Instructor", false),
        SkillEntry("Horse Trader", false),
        SkillEntry("Horse Trainer", false),
        SkillEntry("Horticultural Consultant", false),
        SkillEntry("Horticulturalist", false),
        SkillEntry("Hosiery Mechanic", false),
        SkillEntry("Hosiery Worker", false),
        SkillEntry("Hospital Consultant", false),
        SkillEntry("Hospital Doctor", false),
        SkillEntry("Hospital Manager", false),
        SkillEntry("Hospital Orderly", false),
        SkillEntry("Hospital Technician", false),
        SkillEntry("Hospital Warden", false),
        SkillEntry("Hospital Worker", false),
        SkillEntry("Hostess", false),
        SkillEntry("Hot Foil Printer", false),
        SkillEntry("Hotel Consultant", false),
        SkillEntry("Hotel Worker", false),
        SkillEntry("Hotelier", false),
        SkillEntry("Househusband", false),
        SkillEntry("Housekeeper", false),
        SkillEntry("Housewife", false),
        SkillEntry("Housing Assistant", false),
        SkillEntry("Housing Officer", false),
        SkillEntry("Housing Supervisor", false),
        SkillEntry("Hygienist", false),
        SkillEntry("Hypnotherapist", false),
        SkillEntry("Hypnotist", false),
        SkillEntry("IT Consultant", false),
        SkillEntry("IT Manager", false),
        SkillEntry("IT Trainer", false),
        SkillEntry("Ice Cream Vendor", false),
        SkillEntry("Illustrator", false),
        SkillEntry("Immigration Officer", false),
        SkillEntry("Import Consultant", false),
        SkillEntry("Importer", false),
        SkillEntry("Independent Means", false),
        SkillEntry("Induction Moulder", false),
        SkillEntry("Industrial Chemist", false),
        SkillEntry("Industrial Consultant", false),
        SkillEntry("Injection Moulder", false),
        SkillEntry("Inspector", false),
        SkillEntry("Instructor", false),
        SkillEntry("Instrument Engineer", false),
        SkillEntry("Instrument Maker", false),
        SkillEntry("Instrument Supervisor", false),
        SkillEntry("Instrument Technician", false),
        SkillEntry("Insurance Agent", false),
        SkillEntry("Insurance Assessor", false),
        SkillEntry("Insurance Broker", false),
        SkillEntry("Insurance Consultant", false),
        SkillEntry("Insurance Inspector", false),
        SkillEntry("Insurance Staff", false),
        SkillEntry("Interior Decorator", false),
        SkillEntry("Interior Designer", false),
        SkillEntry("Interpreter", false),
        SkillEntry("Interviewer", false),
        SkillEntry("Inventor", false),
        SkillEntry("Investigator", false),
        SkillEntry("Investment Advisor", false),
        SkillEntry("Investment Banker", false),
        SkillEntry("Investment Manager", false),
        SkillEntry("Investment Strategist", false),
        SkillEntry("Ironmonger", false),
        SkillEntry("Janitor", false),
        SkillEntry("Jazz Composer", false),
        SkillEntry("Jeweller", false),
        SkillEntry("Jewellery", false),
        SkillEntry("Jockey", false),
        SkillEntry("Joiner", false),
        SkillEntry("Joinery Consultant", false),
        SkillEntry("Journalist", false),
        SkillEntry("Judge", false),
        SkillEntry("Keep Fit Instructor", false),
        SkillEntry("Kennel Hand", false),
        SkillEntry("Kitchen Worker", false),
        SkillEntry("Knitter", false),
        SkillEntry("Labelling Operator", false),
        SkillEntry("Laboratory Analyst", false),
        SkillEntry("Labourer", false),
        SkillEntry("Laminator", false),
        SkillEntry("Lampshade Maker", false),
        SkillEntry("Land Agent", false),
        SkillEntry("Land Surveyor", false),
        SkillEntry("Landlady", false),
        SkillEntry("Landlord", false),
        SkillEntry("Landowner", false),
        SkillEntry("Landworker", false),
        SkillEntry("Lathe Operator", false),
        SkillEntry("Laundry Staff", false),
        SkillEntry("Laundry Worker", false),
        SkillEntry("Lavatory Attendant", false),
        SkillEntry("Law Clerk", false),
        SkillEntry("Lawn Mower", false),
        SkillEntry("Lawyer", false),
        SkillEntry("Leaflet Distributor", false),
        SkillEntry("Leather Worker", false),
        SkillEntry("Lecturer", false),
        SkillEntry("Ledger Clerk", false),
        SkillEntry("Legal Advisor", false),
        SkillEntry("Legal Assistant", false),
        SkillEntry("Legal Executive", false),
        SkillEntry("Legal Secretary", false),
        SkillEntry("Letting Agent", false),
        SkillEntry("Liaison Officer", false),
        SkillEntry("Librarian", false),
        SkillEntry("Library Manager", false),
        SkillEntry("Licensed Premises", false),
        SkillEntry("Licensee", false),
        SkillEntry("Licensing", false),
        SkillEntry("Lifeguard", false),
        SkillEntry("Lift Attendant", false),
        SkillEntry("Lift Engineer", false),
        SkillEntry("Lighterman", false),
        SkillEntry("Lighthouse Keeper", false),
        SkillEntry("Lighting Designer", false),
        SkillEntry("Lighting Technician", false),
        SkillEntry("Lime Kiln Attendant", false),
        SkillEntry("Line Manager", false),
        SkillEntry("Line Worker", false),
        SkillEntry("Lineman", false),
        SkillEntry("Linguist", false),
        SkillEntry("Literary Agent", false),
        SkillEntry("Literary Editor", false),
        SkillEntry("Lithographer", false),
        SkillEntry("Litigation Manager", false),
        SkillEntry("Loans Manager", false),
        SkillEntry("Local Government", false),
        SkillEntry("Lock Keeper", false),
        SkillEntry("Locksmith", false),
        SkillEntry("Locum Pharmacist", false),
        SkillEntry("Log Merchant", false),
        SkillEntry("Lorry Driver", false),
        SkillEntry("Loss Adjustor", false),
        SkillEntry("Loss Assessor", false),
        SkillEntry("Lumberjack", false),
        SkillEntry("Machine Fitters", false),
        SkillEntry("Machine Minder", false),
        SkillEntry("Machine Operator", false),
        SkillEntry("Machine Setter", false),
        SkillEntry("Machine Tool", false),
        SkillEntry("Machine Tool Fitter", false),
        SkillEntry("Machinist", false),
        SkillEntry("Magician", false),
        SkillEntry("Magistrate", false),
        SkillEntry("Magistrates Clerk", false),
        SkillEntry("Maid", false),
        SkillEntry("Maintenance Fitter", false),
        SkillEntry("Make Up Artist", false),
        SkillEntry("Manicurist", false),
        SkillEntry("Manufacturing", false),
        SkillEntry("Map Mounter", false),
        SkillEntry("Marble Finisher", false),
        SkillEntry("Marble Mason", false),
        SkillEntry("Marine Broker", false),
        SkillEntry("Marine Consultant", false),
        SkillEntry("Marine Electrician", false),
        SkillEntry("Marine Engineer", false),
        SkillEntry("Marine Geologist", false),
        SkillEntry("Marine Pilot", false),
        SkillEntry("Marine Surveyor", false),
        SkillEntry("Market Gardener", false),
        SkillEntry("Market Research", false),
        SkillEntry("Market Researcher", false),
        SkillEntry("Market Trader", false),
        SkillEntry("Marketing Agent", false),
        SkillEntry("Marketing Assistant", false),
        SkillEntry("Marketing Coordinator", false),
        SkillEntry("Marketing Director", false),
        SkillEntry("Marketing Manager", false),
        SkillEntry("Marquee Erector", false),
        SkillEntry("Massage Therapist", false),
        SkillEntry("Masseur", false),
        SkillEntry("Masseuse", false),
        SkillEntry("Master Mariner", false),
        SkillEntry("Materials Controller", false),
        SkillEntry("Materials Manager", false),
        SkillEntry("Mathematician", false),
        SkillEntry("Maths Teacher", false),
        SkillEntry("Matron", false),
        SkillEntry("Mattress Maker", false),
        SkillEntry("Meat Inspector", false),
        SkillEntry("Meat Wholesaler", false),
        SkillEntry("Mechanic", false),
        SkillEntry("Medal Dealer", false),
        SkillEntry("Medical Advisor", false),
        SkillEntry("Medical Assistant", false),
        SkillEntry("Medical Consultant", false),
        SkillEntry("Medical Officer", false),
        SkillEntry("Medical Physicist", false),
        SkillEntry("Medical Practitioner", false),
        SkillEntry("Medical Researcher", false),
        SkillEntry("Medical Secretary", false),
        SkillEntry("Medical Student", false),
        SkillEntry("Medical Supplier", false),
        SkillEntry("Medical Technician", false),
        SkillEntry("Merchandiser", false),
        SkillEntry("Merchant", false),
        SkillEntry("Merchant Banker", false),
        SkillEntry("Merchant Seaman", false),
        SkillEntry("Messenger", false),
        SkillEntry("Metal Dealer", false),
        SkillEntry("Metal Engineer", false),
        SkillEntry("Metal Polisher", false),
        SkillEntry("Metal Worker", false),
        SkillEntry("Metallurgist", false),
        SkillEntry("Meteorologist", false),
        SkillEntry("Meter Reader", false),
        SkillEntry("Microbiologist", false),
        SkillEntry("Midwife", false),
        SkillEntry("Military Leader", false),
        SkillEntry("Milklady", false),
        SkillEntry("Milkman", false),
        SkillEntry("Mill Operator", false),
        SkillEntry("Mill Worker", false),
        SkillEntry("Miller", false),
        SkillEntry("Milliner", false),
        SkillEntry("Millwright", false),
        SkillEntry("Miner", false),
        SkillEntry("Mineralologist", false),
        SkillEntry("Minibus Driver", false),
        SkillEntry("Minicab Driver", false),
        SkillEntry("Mining Consultant", false),
        SkillEntry("Mining Engineer", false),
        SkillEntry("Money Broker", false),
        SkillEntry("Moneylender", false),
        SkillEntry("Mooring Contractor", false),
        SkillEntry("Mortgage Broker", false),
        SkillEntry("Mortician", false),
        SkillEntry("Motor Dealer", false),
        SkillEntry("Motor Engineer", false),
        SkillEntry("Motor Fitter", false),
        SkillEntry("Motor Mechanic", false),
        SkillEntry("Motor Racing", false),
        SkillEntry("Motor Trader", false),
        SkillEntry("Museum Assistant", false),
        SkillEntry("Museum Attendant", false),
        SkillEntry("Music Teacher", false),
        SkillEntry("Musician", false),
        SkillEntry("Nanny", false),
        SkillEntry("Navigator", false),
        SkillEntry("Negotiator", false),
        SkillEntry("Neurologist", false),
        SkillEntry("Newsagent", false),
        SkillEntry("Night Porter", false),
        SkillEntry("Night Watchman", false),
        SkillEntry("Nuclear Scientist", false),
        SkillEntry("Nun", false),
        SkillEntry("Nurse", false),
        SkillEntry("Nursery Assistant", false),
        SkillEntry("Nursery Nurse", false),
        SkillEntry("Nursery Worker", false),
        SkillEntry("Nurseryman", false),
        SkillEntry("Nursing Assistant", false),
        SkillEntry("Nursing Auxiliary", false),
        SkillEntry("Nursing Manager", false),
        SkillEntry("Nursing Sister", false),
        SkillEntry("Nutritionist", false),
        SkillEntry("Off Shore", false),
        SkillEntry("Office Manager", false),
        SkillEntry("Office Worker", false),
        SkillEntry("Oil Broker", false),
        SkillEntry("Oil Rig Crew", false),
        SkillEntry("Opera Singer", false),
        SkillEntry("Operations", false),
        SkillEntry("Operative", false),
        SkillEntry("Operator", false),
        SkillEntry("Optical", false),
        SkillEntry("Optical Advisor", false),
        SkillEntry("Optical Assistant", false),
        SkillEntry("Optician", false),
        SkillEntry("Optometrist", false),
        SkillEntry("Orchestral", false),
        SkillEntry("Organiser", false),
        SkillEntry("Organist", false),
        SkillEntry("Ornamental", false),
        SkillEntry("Ornithologist", false),
        SkillEntry("Orthopaedic", false),
        SkillEntry("Orthoptist", false),
        SkillEntry("Osteopath", false),
        SkillEntry("Outdoor Pursuits", false),
        SkillEntry("Outreach Worker", false),
        SkillEntry("Packaging", false),
        SkillEntry("Packer", false),
        SkillEntry("Paediatrician", false),
        SkillEntry("Paint Consultant", false),
        SkillEntry("Painter", false),
        SkillEntry("Palaeobotanist", false),
        SkillEntry("Palaeontologist", false),
        SkillEntry("Pallet Maker", false),
        SkillEntry("Panel Beater", false),
        SkillEntry("Paramedic", false),
        SkillEntry("Park Attendant", false),
        SkillEntry("Park Keeper", false),
        SkillEntry("Park Ranger", false),
        SkillEntry("Partition Erector", false),
        SkillEntry("Parts Man", false),
        SkillEntry("Parts Manager", false),
        SkillEntry("Parts Supervisor", false),
        SkillEntry("Party Planner", false),
        SkillEntry("Pasteuriser", false),
        SkillEntry("Pastry Chef", false),
        SkillEntry("Patent Agent", false),
        SkillEntry("Patent Attorney", false),
        SkillEntry("Pathologist", false),
        SkillEntry("Patrolman", false),
        SkillEntry("Pattern Cutter", false),
        SkillEntry("Pattern Maker", false),
        SkillEntry("Pattern Weaver", false),
        SkillEntry("Pawnbroker", false),
        SkillEntry("Payroll Assistant", false),
        SkillEntry("Payroll Clerk", false),
        SkillEntry("Payroll Manager", false),
        SkillEntry("Payroll Supervisor", false),
        SkillEntry("Personnel Officer", false),
        SkillEntry("Pest Controller", false),
        SkillEntry("Pet Minder", false),
        SkillEntry("Pharmacist", false),
        SkillEntry("Philatelist", false),
        SkillEntry("Photographer", false),
        SkillEntry("Physician", false),
        SkillEntry("Physicist", false),
        SkillEntry("Physiologist", false),
        SkillEntry("Physiotherapist", false),
        SkillEntry("Piano Teacher", false),
        SkillEntry("Piano Tuner", false),
        SkillEntry("Picture Editor", false),
        SkillEntry("Picture Framer", false),
        SkillEntry("Picture Reseacher", false),
        SkillEntry("Pig Man", false),
        SkillEntry("Pig Manager", false),
        SkillEntry("Pilot", false),
        SkillEntry("Pipe Fitter", false),
        SkillEntry("Pipe Inspector", false),
        SkillEntry("Pipe Insulator", false),
        SkillEntry("Pipe Layer", false),
        SkillEntry("Planning Engineer", false),
        SkillEntry("Planning Manager", false),
        SkillEntry("Planning Officer", false),
        SkillEntry("Planning Technician", false),
        SkillEntry("Plant Attendant", false),
        SkillEntry("Plant Driver", false),
        SkillEntry("Plant Engineer", false),
        SkillEntry("Plant Fitter", false),
        SkillEntry("Plant Manager", false),
        SkillEntry("Plant Operator", false),
        SkillEntry("Plasterer", false),
        SkillEntry("Plastics Consultant", false),
        SkillEntry("Plastics Engineer", false),
        SkillEntry("Plate Layer", false),
        SkillEntry("Plater", false),
        SkillEntry("Playgroup Assistant", false),
        SkillEntry("Playgroup Leader", false),
        SkillEntry("Plumber", false),
        SkillEntry("Podiatrist", false),
        SkillEntry("Police Officer", false),
        SkillEntry("Polisher", false),
        SkillEntry("Pool Attendant", false),
        SkillEntry("Pools Collector", false),
        SkillEntry("Porter", false),
        SkillEntry("Portfolio Manager", false),
        SkillEntry("Post Sorter", false),
        SkillEntry("Postman", false),
        SkillEntry("Postmaster", false),
        SkillEntry("Postwoman", false),
        SkillEntry("Potter", false),
        SkillEntry("Practice Manager", false),
        SkillEntry("Preacher", false),
        SkillEntry("Precision Engineer", false),
        SkillEntry("Premises", false),
        SkillEntry("Premises Security", false),
        SkillEntry("Press Officer", false),
        SkillEntry("Press Operator", false),
        SkillEntry("Press Setter", false),
        SkillEntry("Presser", false),
        SkillEntry("Priest", false),
        SkillEntry("Print Finisher", false),
        SkillEntry("Printer", false),
        SkillEntry("Prison Chaplain", false),
        SkillEntry("Prison Officer", false),
        SkillEntry("Private Investigator", false),
        SkillEntry("Probation Officer", false),
        SkillEntry("Probation Worker", false),
        SkillEntry("Procurator Fiscal", false),
        SkillEntry("Produce Supervisor", false),
        SkillEntry("Producer", false),
        SkillEntry("Product Installer", false),
        SkillEntry("Product Manager", false),
        SkillEntry("Production Engineer", false),
        SkillEntry("Production Hand", false),
        SkillEntry("Production Manager", false),
        SkillEntry("Production Planner", false),
        SkillEntry("Professional Boxer", false),
        SkillEntry("Professional Racing", false),
        SkillEntry("Professional Wrestler", false),
        SkillEntry("Progress Chaser", false),
        SkillEntry("Progress Clerk", false),
        SkillEntry("Project Co-ordinator", false),
        SkillEntry("Project Engineer", false),
        SkillEntry("Project Leader", false),
        SkillEntry("Project Manager", false),
        SkillEntry("Project Worker", false),
        SkillEntry("Projectionist", false),
        SkillEntry("Promoter", false),
        SkillEntry("Proof Reader", false),
        SkillEntry("Property Buyer", false),
        SkillEntry("Property Dealer", false),
        SkillEntry("Property Developer", false),
        SkillEntry("Property Manager", false),
        SkillEntry("Property Valuer", false),
        SkillEntry("Proprietor", false),
        SkillEntry("Psychiatrist", false),
        SkillEntry("Psychoanalyst", false),
        SkillEntry("Psychologist", false),
        SkillEntry("Psychotherapist", false),
        SkillEntry("Public House Manager", false),
        SkillEntry("Public Relations Of?cer", false),
        SkillEntry("Publican", false),
        SkillEntry("Publicity Manager", false),
        SkillEntry("Publisher", false),
        SkillEntry("Publishing Manager", false),
        SkillEntry("Purchase Clerk", false),
        SkillEntry("Purchase Ledger Clerk", false),
        SkillEntry("Purchasing Assistant", false),
        SkillEntry("Purchasing Manager", false),
        SkillEntry("Purser", false),
        SkillEntry("Quality Controller", false),
        SkillEntry("Quality Engineer", false),
        SkillEntry("Quality Inspector", false),
        SkillEntry("Quality Manager", false),
        SkillEntry("Quality Technician", false),
        SkillEntry("Quantity Surveyor", false),
        SkillEntry("Quarry Worker", false),
        SkillEntry("Racehorse Groom", false),
        SkillEntry("Racing Organiser", false),
        SkillEntry("Radio Controller", false),
        SkillEntry("Radio Director", false),
        SkillEntry("Radio Engineer", false),
        SkillEntry("Radio Operator", false),
        SkillEntry("Radio Presenter", false),
        SkillEntry("Radio Producer", false),
        SkillEntry("Radiographer", false),
        SkillEntry("Radiologist", false),
        SkillEntry("Rally Driver", false),
        SkillEntry("Receptionist", false),
        SkillEntry("Recorder", false),
        SkillEntry("Records Supervisor", false),
        SkillEntry("Recovery Vehicle Coordinator", false),
        SkillEntry("Recreational", false),
        SkillEntry("Recruitment Consultant", false),
        SkillEntry("Rector", false),
        SkillEntry("Reflexologist", false),
        SkillEntry("Refractory Engineer", false),
        SkillEntry("Refrigeration Engineer", false),
        SkillEntry("Refuse Collector", false),
        SkillEntry("Registrar", false),
        SkillEntry("Regulator", false),
        SkillEntry("Relocation Agent", false),
        SkillEntry("Remedial Therapist", false),
        SkillEntry("Rent Collector", false),
        SkillEntry("Rent Offcer", false),
        SkillEntry("Repair Man", false),
        SkillEntry("Repairer", false),
        SkillEntry("Reporter", false),
        SkillEntry("Representative", false),
        SkillEntry("Reprographic Assistant", false),
        SkillEntry("Research Analyst", false),
        SkillEntry("Research Consultant", false),
        SkillEntry("Research Director", false),
        SkillEntry("Research Scientist", false),
        SkillEntry("Research Technician", false),
        SkillEntry("Researcher", false),
        SkillEntry("Resin Caster", false),
        SkillEntry("Restaurant Manager", false),
        SkillEntry("Restaurateur", false),
        SkillEntry("Restorer", false),
        SkillEntry("Retired", false),
        SkillEntry("Revenue Clerk", false),
        SkillEntry("Revenue Officer", false),
        SkillEntry("Riding Instructor", false),
        SkillEntry("Rig Worker", false),
        SkillEntry("Rigger", false),
        SkillEntry("Riveter", false),
        SkillEntry("Road Safety Officer", false),
        SkillEntry("Road Sweeper", false),
        SkillEntry("Road Worker", false),
        SkillEntry("Roadworker", false),
        SkillEntry("Roof Tiler", false),
        SkillEntry("Roofer", false),
        SkillEntry("Rose Grower", false),
        SkillEntry("Royal Marine", false),
        SkillEntry("Rug Maker", false),
        SkillEntry("Saddler", false),
        SkillEntry("Safety Officer", false),
        SkillEntry("Sail Maker", false),
        SkillEntry("Sales Administrator", false),
        SkillEntry("Sales Assistant", false),
        SkillEntry("Sales Director", false),
        SkillEntry("Sales Engineer", false),
        SkillEntry("Sales Executive", false),
        SkillEntry("Sales Manager", false),
        SkillEntry("Sales Representative", false),
        SkillEntry("Sales Support", false),
        SkillEntry("Salesman", false),
        SkillEntry("Saleswoman", false),
        SkillEntry("Sand Blaster", false),
        SkillEntry("Saw Miller", false),
        SkillEntry("Scaffolder", false),
        SkillEntry("School Crossing", false),
        SkillEntry("School Inspector", false),
        SkillEntry("Scientific Officer", false),
        SkillEntry("Scientist", false),
        SkillEntry("Scrap Dealer", false),
        SkillEntry("Screen Printer", false),
        SkillEntry("Screen Writer", false),
        SkillEntry("Script Writer", false),
        SkillEntry("Sculptor", false),
        SkillEntry("Seaman", false),
        SkillEntry("Seamstress", false),
        SkillEntry("Secretary", false),
        SkillEntry("Security Consultant", false),
        SkillEntry("Security Controller", false),
        SkillEntry("Security Guard", false),
        SkillEntry("Security Officer", false),
        SkillEntry("Servant", false),
        SkillEntry("Service Engineer", false),
        SkillEntry("Service Manager", false),
        SkillEntry("Share Dealer", false),
        SkillEntry("Sheet Metal Worker", false),
        SkillEntry("Shelf Filler", false),
        SkillEntry("Shelter Warden", false),
        SkillEntry("Shepherd", false),
        SkillEntry("Sheriff", false),
        SkillEntry("Sheriff Clerk", false),
        SkillEntry("Sheriff Principal", false),
        SkillEntry("Shift Controller", false),
        SkillEntry("Ship Broker", false),
        SkillEntry("Ship Builder", false),
        SkillEntry("Shipping Clerk", false),
        SkillEntry("Shipping Officer", false),
        SkillEntry("Shipwright", false),
        SkillEntry("Shipyard Worker", false),
        SkillEntry("Shoe Maker", false),
        SkillEntry("Shoe Repairer", false),
        SkillEntry("Shooting Instructor", false),
        SkillEntry("Shop Assistant", false),
        SkillEntry("Shop Fitter", false),
        SkillEntry("Shop Keeper", false),
        SkillEntry("Shop Manager", false),
        SkillEntry("Shop Proprietor", false),
        SkillEntry("Shot Blaster", false),
        SkillEntry("Show Jumper", false),
        SkillEntry("Showman", false),
        SkillEntry("Shunter", false),
        SkillEntry("Sign Maker", false),
        SkillEntry("Signalman", false),
        SkillEntry("Signwriter", false),
        SkillEntry("Site Agent", false),
        SkillEntry("Site Engineer", false),
        SkillEntry("Skipper", false),
        SkillEntry("Slater", false),
        SkillEntry("Slaughterman", false),
        SkillEntry("Smallholder", false),
        SkillEntry("Social Worker", false),
        SkillEntry("Software Consultant", false),
        SkillEntry("Software Engineer", false),
        SkillEntry("Soldier", false),
        SkillEntry("Solicitor", false),
        SkillEntry("Song Writer", false),
        SkillEntry("Sound Artist", false),
        SkillEntry("Sound Engineer", false),
        SkillEntry("Sound Technician", false),
        SkillEntry("Special Constable", false),
        SkillEntry("Special Needs", false),
        SkillEntry("Speech Therapist", false),
        SkillEntry("Sports Administrator", false),
        SkillEntry("Sports Coach", false),
        SkillEntry("Sports Commentator", false),
        SkillEntry("Sportsman", false),
        SkillEntry("Sportsperson", false),
        SkillEntry("Sportswoman", false),
        SkillEntry("Spring Maker", false),
        SkillEntry("Stable Hand", false),
        SkillEntry("Staff Nurse", false),
        SkillEntry("Stage Director", false),
        SkillEntry("Stage Hand", false),
        SkillEntry("Stage Manager", false),
        SkillEntry("Stage Mover", false),
        SkillEntry("Station Manager", false),
        SkillEntry("Stationer", false),
        SkillEntry("Statistician", false),
        SkillEntry("Steel Erector", false),
        SkillEntry("Steel Worker", false),
        SkillEntry("Steeplejack", false),
        SkillEntry("Stenographer", false),
        SkillEntry("Steward", false),
        SkillEntry("Stewardess", false),
        SkillEntry("Stock Controller", false),
        SkillEntry("Stock Manager", false),
        SkillEntry("Stockbroker", false),
        SkillEntry("Stockman", false),
        SkillEntry("Stocktaker", false),
        SkillEntry("Stone Cutter", false),
        SkillEntry("Stone Sawyer", false),
        SkillEntry("Stonemason", false),
        SkillEntry("Store Detective", false),
        SkillEntry("Storeman", false),
        SkillEntry("Storewoman", false),
        SkillEntry("Street Entertainer", false),
        SkillEntry("Street Trader", false),
        SkillEntry("Stud Hand", false),
        SkillEntry("Student", false),
        SkillEntry("Student Nurse", false),
        SkillEntry("Student Teacher", false),
        SkillEntry("Studio Manager", false),
        SkillEntry("Sub-Postmaster", false),
        SkillEntry("Sub-Postmistress", false),
        SkillEntry("Supervisor", false),
        SkillEntry("Supply Teacher", false),
        SkillEntry("Surgeon", false),
        SkillEntry("Surveyor", false),
        SkillEntry("Systems Analyst", false),
        SkillEntry("Systems Engineer", false),
        SkillEntry("Systems Manager", false),
        SkillEntry("TV Editor", false),
        SkillEntry("Tachograph Analyst", false),
        SkillEntry("Tacker", false),
        SkillEntry("Tailor", false),
        SkillEntry("Tank Farm Operative", false),
        SkillEntry("Tanker Driver", false),
        SkillEntry("Tanner", false),
        SkillEntry("Tattooist", false),
        SkillEntry("Tax Advisor", false),
        SkillEntry("Tax Analyst", false),
        SkillEntry("Tax Assistant", false),
        SkillEntry("Tax Consultant", false),
        SkillEntry("Tax Inspector", false),
        SkillEntry("Tax Manager", false),
        SkillEntry("Tax Officer", false),
        SkillEntry("Taxi Controller", false),
        SkillEntry("Taxi Driver", false),
        SkillEntry("Taxidermist", false),
        SkillEntry("Tea Blender", false),
        SkillEntry("Tea Taster", false),
        SkillEntry("Teacher", false),
        SkillEntry("Teachers Assistant", false),
        SkillEntry("Technical Advisor", false),
        SkillEntry("Technical Analyst", false),
        SkillEntry("Technical Assistant", false),
        SkillEntry("Technical Author", false),
        SkillEntry("Technical Clerk", false),
        SkillEntry("Technical Co-ordinator", false),
        SkillEntry("Technical Director", false),
        SkillEntry("Technical Editor", false),
        SkillEntry("Technical Engineer", false),
        SkillEntry("Technical Illustrator", false),
        SkillEntry("Technical Instructor", false),
        SkillEntry("Technical Liaison", false),
        SkillEntry("Technical Manager", false),
        SkillEntry("Technician", false),
        SkillEntry("Telecommunication", false),
        SkillEntry("Telecommunications", false),
        SkillEntry("Telegraphist", false),
        SkillEntry("Telemarketeer", false),
        SkillEntry("Telephone Engineer", false),
        SkillEntry("Telephonist", false),
        SkillEntry("Telesales Person", false),
        SkillEntry("Television Director", false),
        SkillEntry("Television Engineer", false),
        SkillEntry("Television Presenter", false),
        SkillEntry("Television Producer", false),
        SkillEntry("Telex Operator", false),
        SkillEntry("Temperature Time", false),
        SkillEntry("Tennis Coach", false),
        SkillEntry("Textile Consultant", false),
        SkillEntry("Textile Engineer", false),
        SkillEntry("Textile Technician", false),
        SkillEntry("Textile Worker", false),
        SkillEntry("Thatcher", false),
        SkillEntry("Theatre Manager", false),
        SkillEntry("Theatre Technician", false),
        SkillEntry("Theatrical Agent", false),
        SkillEntry("Therapist", false),
        SkillEntry("Thermal Engineer", false),
        SkillEntry("Thermal Insulator", false),
        SkillEntry("Ticket Agent", false),
        SkillEntry("Ticket Inspector", false),
        SkillEntry("Tiler", false),
        SkillEntry("Timber Inspector", false),
        SkillEntry("Timber Worker", false),
        SkillEntry("Tobacconist", false),
        SkillEntry("Toll Collector", false),
        SkillEntry("Tool Maker", false),
        SkillEntry("Tour Agent", false),
        SkillEntry("Tour Guide", false),
        SkillEntry("Town Clerk", false),
        SkillEntry("Town Planner", false),
        SkillEntry("Toy Maker", false),
        SkillEntry("Toy Trader", false),
        SkillEntry("Track Worker", false),
        SkillEntry("Tractor Driver", false),
        SkillEntry("Tractor Mechanic", false),
        SkillEntry("Trade Mark Agent", false),
        SkillEntry("Trade Union Official", false),
        SkillEntry("Trading Standards", false),
        SkillEntry("Traffic Warden", false),
        SkillEntry("Train Driver", false),
        SkillEntry("Trainee Manager", false),
        SkillEntry("Training Advisor", false),
        SkillEntry("Training Assistant", false),
        SkillEntry("Training Co-ordinator", false),
        SkillEntry("Training Consultant", false),
        SkillEntry("Training Instructor", false),
        SkillEntry("Training Manager", false),
        SkillEntry("Training Officer", false),
        SkillEntry("Transcriber", false),
        SkillEntry("Translator", false),
        SkillEntry("Transport Clerk", false),
        SkillEntry("Transport Consultant", false),
        SkillEntry("Transport Controller", false),
        SkillEntry("Transport Engineer", false),
        SkillEntry("Transport Manager", false),
        SkillEntry("Transport Officer", false),
        SkillEntry("Transport Planner", false),
        SkillEntry("Travel Agent", false),
        SkillEntry("Travel Clerk", false),
        SkillEntry("Travel Consultant", false),
        SkillEntry("Travel Courier", false),
        SkillEntry("Travel Guide", false),
        SkillEntry("Travel Guide Writer", false),
        SkillEntry("Travel Representative", false),
        SkillEntry("Travelling Showman", false),
        SkillEntry("Treasurer", false),
        SkillEntry("Tree Feller", false),
        SkillEntry("Tree Surgeon", false),
        SkillEntry("Trichologist", false),
        SkillEntry("Trinity House Pilot", false),
        SkillEntry("Trout Farmer", false),
        SkillEntry("Tug Skipper", false),
        SkillEntry("Tunneller", false),
        SkillEntry("Turf Accountant", false),
        SkillEntry("Turkey Farmer", false),
        SkillEntry("Turner", false),
        SkillEntry("Tutor", false),
        SkillEntry("Typesetter", false),
        SkillEntry("Typewriter Engineer", false),
        SkillEntry("Typist", false),
        SkillEntry("Tyre Builder", false),
        SkillEntry("Tyre Fitter", false),
        SkillEntry("Tyre Inspector", false),
        SkillEntry("Tyre Technician", false),
        SkillEntry("Undertaker", false),
        SkillEntry("Underwriter", false),
        SkillEntry("Upholsterer", false),
        SkillEntry("Valuer", false),
        SkillEntry("Valve Technician", false),
        SkillEntry("Van Driver", false),
        SkillEntry("Vehicle Assessor", false),
        SkillEntry("Vehicle Body Worker", false),
        SkillEntry("Vehicle Engineer", false),
        SkillEntry("Vehicle Technician", false),
        SkillEntry("Ventriloquist", false),
        SkillEntry("Verger", false),
        SkillEntry("Veterinary Surgeon", false),
        SkillEntry("Vicar", false),
        SkillEntry("Video Artist", false),
        SkillEntry("Violin Maker", false),
        SkillEntry("Violinist", false),
        SkillEntry("Voluntary Worker", false),
        SkillEntry("Wages Clerk", false),
        SkillEntry("Waiter", false),
        SkillEntry("Waitress", false),
        SkillEntry("Warden", false),
        SkillEntry("Warehouse Manager", false),
        SkillEntry("Warehouseman", false),
        SkillEntry("Warehousewoman", false),
        SkillEntry("Watchmaker", false),
        SkillEntry("Weaver", false),
        SkillEntry("Weighbridge Clerk", false),
        SkillEntry("Weighbridge Operator", false),
        SkillEntry("Welder", false),
        SkillEntry("Welfare Assistant", false),
        SkillEntry("Welfare Officer", false),
        SkillEntry("Welfare Rights Officer", false),
        SkillEntry("Wheel Clamper", false),
        SkillEntry("Wholesale Newspaper", false),
        SkillEntry("Window Cleaner", false),
        SkillEntry("Window Dresser", false),
        SkillEntry("Windscreen Fitter", false),
        SkillEntry("Wine Merchant", false),
        SkillEntry("Wood Carver", false),
        SkillEntry("Wood Cutter", false),
        SkillEntry("Wood Worker", false),
        SkillEntry("Word Processing Operator", false),
        SkillEntry("Works Manager", false),
        SkillEntry("Writer", false),
        SkillEntry("Yacht Master", false),
        SkillEntry("Yard Manager", false),
        SkillEntry("Youth Hostel Warden", false),
        SkillEntry("Youth Worker", false),
        SkillEntry("Zoo Keeper", false),
        SkillEntry("Zoo Manager", false),
        SkillEntry("Zoologist", false)
    )
}