//package it.polito.ma.g14.timebank
//
//import android.app.Activity
//import android.content.Intent
//import android.os.Bundle
//import android.view.Menu
//import android.view.MenuInflater
//import android.widget.LinearLayout
//import android.widget.SearchView
//import androidx.appcompat.app.AppCompatActivity
//import androidx.recyclerview.widget.LinearLayoutManager
//import androidx.recyclerview.widget.RecyclerView
//import it.polito.listapplication.Item
//import it.polito.listapplication.ItemAdapter
//
//class ChooseSkillsActivity : AppCompatActivity() {
//
//    var skill_entry_holder : LinearLayout? = null
//    var skill_list : MutableList<Item> = mutableListOf(
//        Item("Accountant", false),
//        Item("Accounts Assistant", false),
//        Item("Accounts Clerk", false),
//        Item("Accounts Manager", false),
//        Item("Accounts Staff", false),
//        Item("Acoustic Engineer", false),
//        Item("Actor", false),
//        Item("Actress", false),
//        Item("Actuary", false),
//        Item("Acupuncturist", false),
//        Item("Adjustor", false),
//        Item("Administration Assistant", false),
//        Item("Administration Clerk", false),
//        Item("Administration Manager", false),
//        Item("Administration Staff", false),
//        Item("Administrator", false),
//        Item("Advertising Agent", false),
//        Item("Advertising Assistant", false),
//        Item("Advertising Clerk", false),
//        Item("Advertising Contractor", false),
//        Item("Advertising Executive", false),
//        Item("Advertising Manager", false),
//        Item("Advertising Staff", false),
//        Item("Aerial Erector", false),
//        Item("Aerobic Instructor", false),
//        Item("Aeronautical Engineer", false),
//        Item("Agent", false),
//        Item("Air Traffic Controller", false),
//        Item("Aircraft Designer", false),
//        Item("Aircraft Engineer", false),
//        Item("Aircraft Maintenance Engineer", false),
//        Item("Aircraft Surface Finisher", false),
//        Item("Airman", false),
//        Item("Airport Controller", false),
//        Item("Airport Manager", false),
//        Item("Almoner", false),
//        Item("Ambulance Controller", false),
//        Item("Ambulance Crew", false),
//        Item("Ambulance Driver", false),
//        Item("Amusement Arcade Worker", false),
//        Item("Anaesthetist", false),
//        Item("Analyst", false),
//        Item("Analytical Chemist", false),
//        Item("Animal Breeder", false),
//        Item("Anthropologist", false),
//        Item("Antique Dealer", false),
//        Item("Applications Engineer", false),
//        Item("Applications Programmer", false),
//        Item("Arbitrator", false),
//        Item("Arborist", false),
//        Item("Archaeologist", false),
//        Item("Architect", false),
//        Item("Archivist", false),
//        Item("Area Manager", false),
//        Item("Armourer", false),
//        Item("Aromatherapist", false),
//        Item("Art Critic", false),
//        Item("Art Dealer", false),
//        Item("Art Historian", false),
//        Item("Art Restorer", false),
//        Item("Artexer", false),
//        Item("Artist", false),
//        Item("Arts", false),
//        Item("Assembly Worker", false),
//        Item("Assessor", false),
//        Item("Assistant", false),
//        Item("Assistant Caretaker", false),
//        Item("Assistant Cook", false),
//        Item("Assistant Manager", false),
//        Item("Assistant Nurse", false),
//        Item("Assistant Teacher", false),
//        Item("Astrologer", false),
//        Item("Astronomer", false),
//        Item("Attendant", false),
//        Item("Au Pair", false),
//        Item("Auction Worker", false),
//        Item("Auctioneer", false),
//        Item("Audiologist", false),
//        Item("Audit Clerk", false),
//        Item("Audit Manager", false),
//        Item("Auditor", false),
//        Item("Auto Electrician", false),
//        Item("Auxiliary Nurse", false),
//        Item("Bacon Curer", false),
//        Item("Baggage Handler", false),
//        Item("Bailiff", false),
//        Item("Baker", false),
//        Item("Bakery Assistant", false),
//        Item("Bakery Manager", false),
//        Item("Bakery Operator", false),
//        Item("Balloonist", false),
//        Item("Bank Clerk", false),
//        Item("Bank Manager", false),
//        Item("Bank Messenger", false),
//        Item("Baptist Minister", false),
//        Item("Bar Manager", false),
//        Item("Bar Steward", false),
//        Item("Barber", false),
//        Item("Barmaid", false),
//        Item("Barman", false),
//        Item("Barrister", false),
//        Item("Beautician", false),
//        Item("Beauty Therapist", false),
//        Item("Betting Shop", false),
//        Item("Bill Poster", false),
//        Item("Bingo Caller", false),
//        Item("Biochemist", false),
//        Item("Biologist", false),
//        Item("Blacksmith", false),
//        Item("Blind Assembler", false),
//        Item("Blind Fitter", false),
//        Item("Blinds Installer", false),
//        Item("Boat Builder", false),
//        Item("Body Fitter", false),
//        Item("Bodyguard", false),
//        Item("Bodyshop", false),
//        Item("Book Binder", false),
//        Item("Book Seller", false),
//        Item("Book-Keeper", false),
//        Item("Booking Agent", false),
//        Item("Booking Clerk", false),
//        Item("Bookmaker", false),
//        Item("Botanist", false),
//        Item("Branch Manager", false),
//        Item("Breeder", false),
//        Item("Brewer", false),
//        Item("Brewery Manager", false),
//        Item("Brewery Worker", false),
//        Item("Bricklayer", false),
//        Item("Broadcaster", false),
//        Item("Builder", false),
//        Item("Builders Labourer", false),
//        Item("Building Advisor", false),
//        Item("Building Control", false),
//        Item("Building Engineer", false),
//        Item("Building Estimator", false),
//        Item("Building Foreman", false),
//        Item("Building Inspector", false),
//        Item("Building Manager", false),
//        Item("Building Surveyor", false),
//        Item("Bursar", false),
//        Item("Bus Company", false),
//        Item("Bus Conductor", false),
//        Item("Bus Driver", false),
//        Item("Bus Mechanic", false),
//        Item("Bus Valeter", false),
//        Item("Business Consultant", false),
//        Item("Business Proprietor", false),
//        Item("Butcher", false),
//        Item("Butchery Manager", false),
//        Item("Butler", false),
//        Item("Buyer", false),
//        Item("Cab Driver", false),
//        Item("Cabinet Maker", false),
//        Item("Cable Contractor", false),
//        Item("Cable Jointer", false),
//        Item("Cable TV Installer", false),
//        Item("Cafe Owner", false),
//        Item("Cafe Staff", false),
//        Item("Cafe Worker", false),
//        Item("Calibration Manager", false),
//        Item("Camera Repairer", false),
//        Item("Cameraman", false),
//        Item("Car Dealer", false),
//        Item("Car Delivery Driver", false),
//        Item("Car Park Attendant", false),
//        Item("Car Salesman", false),
//        Item("Car Valet", false),
//        Item("Car Wash Attendant", false),
//        Item("Care Assistant", false),
//        Item("Care Manager", false),
//        Item("Careers Advisor", false),
//        Item("Careers Officer", false),
//        Item("Caretaker", false),
//        Item("Cargo Operator", false),
//        Item("Carpenter", false),
//        Item("Carpet Cleaner", false),
//        Item("Carpet Fitter", false),
//        Item("Carpet Retailer", false),
//        Item("Carphone Fitter", false),
//        Item("Cartographer", false),
//        Item("Cartoonist", false),
//        Item("Cashier", false),
//        Item("Casual Worker", false),
//        Item("Caterer", false),
//        Item("Catering Consultant", false),
//        Item("Catering Manager", false),
//        Item("Catering Staff", false),
//        Item("Caulker", false),
//        Item("Ceiling Contractor", false),
//        Item("Ceiling Fixer", false),
//        Item("Cellarman", false),
//        Item("Chambermaid", false),
//        Item("Chandler", false),
//        Item("Chaplain", false),
//        Item("Charge Hand", false),
//        Item("Charity Worker", false),
//        Item("Chartered", false),
//        Item("Chartered Accountant", false),
//        Item("Chauffeur", false),
//        Item("Chef", false),
//        Item("Chemist", false),
//        Item("Chicken Chaser", false),
//        Item("Child Minder", false),
//        Item("Childminder", false),
//        Item("Chimney Sweep", false),
//        Item("China Restorer", false),
//        Item("Chiropodist", false),
//        Item("Chiropractor", false),
//        Item("Choreographer", false),
//        Item("Church Officer", false),
//        Item("Church Warden", false),
//        Item("Cinema Manager", false),
//        Item("Circus Proprietor", false),
//        Item("Circus Worker", false),
//        Item("Civil Engineer", false),
//        Item("Civil Servant", false),
//        Item("Claims Adjustor", false),
//        Item("Claims Assessor", false),
//        Item("Claims Manager", false),
//        Item("Clairvoyant", false),
//        Item("Classroom Aide", false),
//        Item("Cleaner", false),
//        Item("Clergyman", false),
//        Item("Cleric", false),
//        Item("Clerk", false),
//        Item("Commissioned", false),
//        Item("Consultant", false),
//        Item("Coroner", false),
//        Item("Councillor", false),
//        Item("Counsellor", false),
//        Item("Dealer", false),
//        Item("Decorator", false),
//        Item("Delivery Driver", false),
//        Item("Doctor", false),
//        Item("Driver", false),
//        Item("Economist", false),
//        Item("Editor", false),
//        Item("Employee", false),
//        Item("Employment", false),
//        Item("Engineer", false),
//        Item("English Teacher", false),
//        Item("Entertainer", false),
//        Item("Envoy", false),
//        Item("Executive", false),
//        Item("Farmer", false),
//        Item("Fireman", false),
//        Item("Floor Layer", false),
//        Item("Floor Manager", false),
//        Item("Florist", false),
//        Item("Flour Miller", false),
//        Item("Flower Arranger", false),
//        Item("Flying Instructor", false),
//        Item("Foam Convertor", false),
//        Item("Food Processor", false),
//        Item("Footballer", false),
//        Item("Foreman", false),
//        Item("Forensic Scientist", false),
//        Item("Forest Ranger", false),
//        Item("Forester", false),
//        Item("Fork Lift Truck Driver", false),
//        Item("Forwarding Agent", false),
//        Item("Foster Parent", false),
//        Item("Foundry Worker", false),
//        Item("Fraud Investigator", false),
//        Item("French Polisher", false),
//        Item("Fruiterer", false),
//        Item("Fuel Merchant", false),
//        Item("Fund Raiser", false),
//        Item("Funeral Director", false),
//        Item("Funeral Furnisher", false),
//        Item("Furnace Man", false),
//        Item("Furniture Dealer", false),
//        Item("Furniture Remover", false),
//        Item("Furniture Restorer", false),
//        Item("Furrier", false),
//        Item("Gallery Owner", false),
//        Item("Gambler", false),
//        Item("Gamekeeper", false),
//        Item("Gaming Board Inspector", false),
//        Item("Gaming Club Manager", false),
//        Item("Gaming Club Proprietor", false),
//        Item("Garage Attendant", false),
//        Item("Garage Foreman", false),
//        Item("Garage Manager", false),
//        Item("Garda", false),
//        Item("Garden Designer", false),
//        Item("Gardener", false),
//        Item("Gas Fitter", false),
//        Item("Gas Mechanic", false),
//        Item("Gas Technician", false),
//        Item("Gate Keeper", false),
//        Item("Genealogist", false),
//        Item("General Practitioner", false),
//        Item("Geologist", false),
//        Item("Geophysicist", false),
//        Item("Gilder", false),
//        Item("Glass Worker", false),
//        Item("Glazier", false),
//        Item("Goldsmith", false),
//        Item("Golf Caddy", false),
//        Item("Golf Club Professional", false),
//        Item("Golfer", false),
//        Item("Goods Handler", false),
//        Item("Governor", false),
//        Item("Granite Technician", false),
//        Item("Graphic Designer", false),
//        Item("Graphologist", false),
//        Item("Grave Digger", false),
//        Item("Gravel Merchant", false),
//        Item("Green Keeper", false),
//        Item("Greengrocer", false),
//        Item("Grocer", false),
//        Item("Groom", false),
//        Item("Ground Worker", false),
//        Item("Groundsman", false),
//        Item("Guest House Owner", false),
//        Item("Guest House Proprietor", false),
//        Item("Gun Smith", false),
//        Item("Gynaecologist", false),
//        Item("HGV Driver", false),
//        Item("HGV Mechanic", false),
//        Item("Hairdresser", false),
//        Item("Handyman", false),
//        Item("Hardware Dealer", false),
//        Item("Haulage Contractor", false),
//        Item("Hawker", false),
//        Item("Health Advisor", false),
//        Item("Health And Safety", false),
//        Item("Health Care Assistant", false),
//        Item("Health Consultant", false),
//        Item("Health Nurse", false),
//        Item("Health Planner", false),
//        Item("Health Service", false),
//        Item("Health Therapist", false),
//        Item("Health Visitor", false),
//        Item("Hearing Therapist", false),
//        Item("Heating Engineer", false),
//        Item("Herbalist", false),
//        Item("Highway Inspector", false),
//        Item("Hire Car Driver", false),
//        Item("Historian", false),
//        Item("History Teacher", false),
//        Item("Hod Carrier", false),
//        Item("Home Economist", false),
//        Item("Home Help", false),
//        Item("Homecare Manager", false),
//        Item("Homeopath", false),
//        Item("Homeworker", false),
//        Item("Hop Merchant", false),
//        Item("Horse Breeder", false),
//        Item("Horse Dealer", false),
//        Item("Horse Riding Instructor", false),
//        Item("Horse Trader", false),
//        Item("Horse Trainer", false),
//        Item("Horticultural Consultant", false),
//        Item("Horticulturalist", false),
//        Item("Hosiery Mechanic", false),
//        Item("Hosiery Worker", false),
//        Item("Hospital Consultant", false),
//        Item("Hospital Doctor", false),
//        Item("Hospital Manager", false),
//        Item("Hospital Orderly", false),
//        Item("Hospital Technician", false),
//        Item("Hospital Warden", false),
//        Item("Hospital Worker", false),
//        Item("Hostess", false),
//        Item("Hot Foil Printer", false),
//        Item("Hotel Consultant", false),
//        Item("Hotel Worker", false),
//        Item("Hotelier", false),
//        Item("Househusband", false),
//        Item("Housekeeper", false),
//        Item("Housewife", false),
//        Item("Housing Assistant", false),
//        Item("Housing Officer", false),
//        Item("Housing Supervisor", false),
//        Item("Hygienist", false),
//        Item("Hypnotherapist", false),
//        Item("Hypnotist", false),
//        Item("IT Consultant", false),
//        Item("IT Manager", false),
//        Item("IT Trainer", false),
//        Item("Ice Cream Vendor", false),
//        Item("Illustrator", false),
//        Item("Immigration Officer", false),
//        Item("Import Consultant", false),
//        Item("Importer", false),
//        Item("Independent Means", false),
//        Item("Induction Moulder", false),
//        Item("Industrial Chemist", false),
//        Item("Industrial Consultant", false),
//        Item("Injection Moulder", false),
//        Item("Inspector", false),
//        Item("Instructor", false),
//        Item("Instrument Engineer", false),
//        Item("Instrument Maker", false),
//        Item("Instrument Supervisor", false),
//        Item("Instrument Technician", false),
//        Item("Insurance Agent", false),
//        Item("Insurance Assessor", false),
//        Item("Insurance Broker", false),
//        Item("Insurance Consultant", false),
//        Item("Insurance Inspector", false),
//        Item("Insurance Staff", false),
//        Item("Interior Decorator", false),
//        Item("Interior Designer", false),
//        Item("Interpreter", false),
//        Item("Interviewer", false),
//        Item("Inventor", false),
//        Item("Investigator", false),
//        Item("Investment Advisor", false),
//        Item("Investment Banker", false),
//        Item("Investment Manager", false),
//        Item("Investment Strategist", false),
//        Item("Ironmonger", false),
//        Item("Janitor", false),
//        Item("Jazz Composer", false),
//        Item("Jeweller", false),
//        Item("Jewellery", false),
//        Item("Jockey", false),
//        Item("Joiner", false),
//        Item("Joinery Consultant", false),
//        Item("Journalist", false),
//        Item("Judge", false),
//        Item("Keep Fit Instructor", false),
//        Item("Kennel Hand", false),
//        Item("Kitchen Worker", false),
//        Item("Knitter", false),
//        Item("Labelling Operator", false),
//        Item("Laboratory Analyst", false),
//        Item("Labourer", false),
//        Item("Laminator", false),
//        Item("Lampshade Maker", false),
//        Item("Land Agent", false),
//        Item("Land Surveyor", false),
//        Item("Landlady", false),
//        Item("Landlord", false),
//        Item("Landowner", false),
//        Item("Landworker", false),
//        Item("Lathe Operator", false),
//        Item("Laundry Staff", false),
//        Item("Laundry Worker", false),
//        Item("Lavatory Attendant", false),
//        Item("Law Clerk", false),
//        Item("Lawn Mower", false),
//        Item("Lawyer", false),
//        Item("Leaflet Distributor", false),
//        Item("Leather Worker", false),
//        Item("Lecturer", false),
//        Item("Ledger Clerk", false),
//        Item("Legal Advisor", false),
//        Item("Legal Assistant", false),
//        Item("Legal Executive", false),
//        Item("Legal Secretary", false),
//        Item("Letting Agent", false),
//        Item("Liaison Officer", false),
//        Item("Librarian", false),
//        Item("Library Manager", false),
//        Item("Licensed Premises", false),
//        Item("Licensee", false),
//        Item("Licensing", false),
//        Item("Lifeguard", false),
//        Item("Lift Attendant", false),
//        Item("Lift Engineer", false),
//        Item("Lighterman", false),
//        Item("Lighthouse Keeper", false),
//        Item("Lighting Designer", false),
//        Item("Lighting Technician", false),
//        Item("Lime Kiln Attendant", false),
//        Item("Line Manager", false),
//        Item("Line Worker", false),
//        Item("Lineman", false),
//        Item("Linguist", false),
//        Item("Literary Agent", false),
//        Item("Literary Editor", false),
//        Item("Lithographer", false),
//        Item("Litigation Manager", false),
//        Item("Loans Manager", false),
//        Item("Local Government", false),
//        Item("Lock Keeper", false),
//        Item("Locksmith", false),
//        Item("Locum Pharmacist", false),
//        Item("Log Merchant", false),
//        Item("Lorry Driver", false),
//        Item("Loss Adjustor", false),
//        Item("Loss Assessor", false),
//        Item("Lumberjack", false),
//        Item("Machine Fitters", false),
//        Item("Machine Minder", false),
//        Item("Machine Operator", false),
//        Item("Machine Setter", false),
//        Item("Machine Tool", false),
//        Item("Machine Tool Fitter", false),
//        Item("Machinist", false),
//        Item("Magician", false),
//        Item("Magistrate", false),
//        Item("Magistrates Clerk", false),
//        Item("Maid", false),
//        Item("Maintenance Fitter", false),
//        Item("Make Up Artist", false),
//        Item("Manicurist", false),
//        Item("Manufacturing", false),
//        Item("Map Mounter", false),
//        Item("Marble Finisher", false),
//        Item("Marble Mason", false),
//        Item("Marine Broker", false),
//        Item("Marine Consultant", false),
//        Item("Marine Electrician", false),
//        Item("Marine Engineer", false),
//        Item("Marine Geologist", false),
//        Item("Marine Pilot", false),
//        Item("Marine Surveyor", false),
//        Item("Market Gardener", false),
//        Item("Market Research", false),
//        Item("Market Researcher", false),
//        Item("Market Trader", false),
//        Item("Marketing Agent", false),
//        Item("Marketing Assistant", false),
//        Item("Marketing Coordinator", false),
//        Item("Marketing Director", false),
//        Item("Marketing Manager", false),
//        Item("Marquee Erector", false),
//        Item("Massage Therapist", false),
//        Item("Masseur", false),
//        Item("Masseuse", false),
//        Item("Master Mariner", false),
//        Item("Materials Controller", false),
//        Item("Materials Manager", false),
//        Item("Mathematician", false),
//        Item("Maths Teacher", false),
//        Item("Matron", false),
//        Item("Mattress Maker", false),
//        Item("Meat Inspector", false),
//        Item("Meat Wholesaler", false),
//        Item("Mechanic", false),
//        Item("Medal Dealer", false),
//        Item("Medical Advisor", false),
//        Item("Medical Assistant", false),
//        Item("Medical Consultant", false),
//        Item("Medical Officer", false),
//        Item("Medical Physicist", false),
//        Item("Medical Practitioner", false),
//        Item("Medical Researcher", false),
//        Item("Medical Secretary", false),
//        Item("Medical Student", false),
//        Item("Medical Supplier", false),
//        Item("Medical Technician", false),
//        Item("Merchandiser", false),
//        Item("Merchant", false),
//        Item("Merchant Banker", false),
//        Item("Merchant Seaman", false),
//        Item("Messenger", false),
//        Item("Metal Dealer", false),
//        Item("Metal Engineer", false),
//        Item("Metal Polisher", false),
//        Item("Metal Worker", false),
//        Item("Metallurgist", false),
//        Item("Meteorologist", false),
//        Item("Meter Reader", false),
//        Item("Microbiologist", false),
//        Item("Midwife", false),
//        Item("Military Leader", false),
//        Item("Milklady", false),
//        Item("Milkman", false),
//        Item("Mill Operator", false),
//        Item("Mill Worker", false),
//        Item("Miller", false),
//        Item("Milliner", false),
//        Item("Millwright", false),
//        Item("Miner", false),
//        Item("Mineralologist", false),
//        Item("Minibus Driver", false),
//        Item("Minicab Driver", false),
//        Item("Mining Consultant", false),
//        Item("Mining Engineer", false),
//        Item("Money Broker", false),
//        Item("Moneylender", false),
//        Item("Mooring Contractor", false),
//        Item("Mortgage Broker", false),
//        Item("Mortician", false),
//        Item("Motor Dealer", false),
//        Item("Motor Engineer", false),
//        Item("Motor Fitter", false),
//        Item("Motor Mechanic", false),
//        Item("Motor Racing", false),
//        Item("Motor Trader", false),
//        Item("Museum Assistant", false),
//        Item("Museum Attendant", false),
//        Item("Music Teacher", false),
//        Item("Musician", false),
//        Item("Nanny", false),
//        Item("Navigator", false),
//        Item("Negotiator", false),
//        Item("Neurologist", false),
//        Item("Newsagent", false),
//        Item("Night Porter", false),
//        Item("Night Watchman", false),
//        Item("Nuclear Scientist", false),
//        Item("Nun", false),
//        Item("Nurse", false),
//        Item("Nursery Assistant", false),
//        Item("Nursery Nurse", false),
//        Item("Nursery Worker", false),
//        Item("Nurseryman", false),
//        Item("Nursing Assistant", false),
//        Item("Nursing Auxiliary", false),
//        Item("Nursing Manager", false),
//        Item("Nursing Sister", false),
//        Item("Nutritionist", false),
//        Item("Off Shore", false),
//        Item("Office Manager", false),
//        Item("Office Worker", false),
//        Item("Oil Broker", false),
//        Item("Oil Rig Crew", false),
//        Item("Opera Singer", false),
//        Item("Operations", false),
//        Item("Operative", false),
//        Item("Operator", false),
//        Item("Optical", false),
//        Item("Optical Advisor", false),
//        Item("Optical Assistant", false),
//        Item("Optician", false),
//        Item("Optometrist", false),
//        Item("Orchestral", false),
//        Item("Organiser", false),
//        Item("Organist", false),
//        Item("Ornamental", false),
//        Item("Ornithologist", false),
//        Item("Orthopaedic", false),
//        Item("Orthoptist", false),
//        Item("Osteopath", false),
//        Item("Outdoor Pursuits", false),
//        Item("Outreach Worker", false),
//        Item("Packaging", false),
//        Item("Packer", false),
//        Item("Paediatrician", false),
//        Item("Paint Consultant", false),
//        Item("Painter", false),
//        Item("Palaeobotanist", false),
//        Item("Palaeontologist", false),
//        Item("Pallet Maker", false),
//        Item("Panel Beater", false),
//        Item("Paramedic", false),
//        Item("Park Attendant", false),
//        Item("Park Keeper", false),
//        Item("Park Ranger", false),
//        Item("Partition Erector", false),
//        Item("Parts Man", false),
//        Item("Parts Manager", false),
//        Item("Parts Supervisor", false),
//        Item("Party Planner", false),
//        Item("Pasteuriser", false),
//        Item("Pastry Chef", false),
//        Item("Patent Agent", false),
//        Item("Patent Attorney", false),
//        Item("Pathologist", false),
//        Item("Patrolman", false),
//        Item("Pattern Cutter", false),
//        Item("Pattern Maker", false),
//        Item("Pattern Weaver", false),
//        Item("Pawnbroker", false),
//        Item("Payroll Assistant", false),
//        Item("Payroll Clerk", false),
//        Item("Payroll Manager", false),
//        Item("Payroll Supervisor", false),
//        Item("Personnel Officer", false),
//        Item("Pest Controller", false),
//        Item("Pet Minder", false),
//        Item("Pharmacist", false),
//        Item("Philatelist", false),
//        Item("Photographer", false),
//        Item("Physician", false),
//        Item("Physicist", false),
//        Item("Physiologist", false),
//        Item("Physiotherapist", false),
//        Item("Piano Teacher", false),
//        Item("Piano Tuner", false),
//        Item("Picture Editor", false),
//        Item("Picture Framer", false),
//        Item("Picture Reseacher", false),
//        Item("Pig Man", false),
//        Item("Pig Manager", false),
//        Item("Pilot", false),
//        Item("Pipe Fitter", false),
//        Item("Pipe Inspector", false),
//        Item("Pipe Insulator", false),
//        Item("Pipe Layer", false),
//        Item("Planning Engineer", false),
//        Item("Planning Manager", false),
//        Item("Planning Officer", false),
//        Item("Planning Technician", false),
//        Item("Plant Attendant", false),
//        Item("Plant Driver", false),
//        Item("Plant Engineer", false),
//        Item("Plant Fitter", false),
//        Item("Plant Manager", false),
//        Item("Plant Operator", false),
//        Item("Plasterer", false),
//        Item("Plastics Consultant", false),
//        Item("Plastics Engineer", false),
//        Item("Plate Layer", false),
//        Item("Plater", false),
//        Item("Playgroup Assistant", false),
//        Item("Playgroup Leader", false),
//        Item("Plumber", false),
//        Item("Podiatrist", false),
//        Item("Police Officer", false),
//        Item("Polisher", false),
//        Item("Pool Attendant", false),
//        Item("Pools Collector", false),
//        Item("Porter", false),
//        Item("Portfolio Manager", false),
//        Item("Post Sorter", false),
//        Item("Postman", false),
//        Item("Postmaster", false),
//        Item("Postwoman", false),
//        Item("Potter", false),
//        Item("Practice Manager", false),
//        Item("Preacher", false),
//        Item("Precision Engineer", false),
//        Item("Premises", false),
//        Item("Premises Security", false),
//        Item("Press Officer", false),
//        Item("Press Operator", false),
//        Item("Press Setter", false),
//        Item("Presser", false),
//        Item("Priest", false),
//        Item("Print Finisher", false),
//        Item("Printer", false),
//        Item("Prison Chaplain", false),
//        Item("Prison Officer", false),
//        Item("Private Investigator", false),
//        Item("Probation Officer", false),
//        Item("Probation Worker", false),
//        Item("Procurator Fiscal", false),
//        Item("Produce Supervisor", false),
//        Item("Producer", false),
//        Item("Product Installer", false),
//        Item("Product Manager", false),
//        Item("Production Engineer", false),
//        Item("Production Hand", false),
//        Item("Production Manager", false),
//        Item("Production Planner", false),
//        Item("Professional Boxer", false),
//        Item("Professional Racing", false),
//        Item("Professional Wrestler", false),
//        Item("Progress Chaser", false),
//        Item("Progress Clerk", false),
//        Item("Project Co-ordinator", false),
//        Item("Project Engineer", false),
//        Item("Project Leader", false),
//        Item("Project Manager", false),
//        Item("Project Worker", false),
//        Item("Projectionist", false),
//        Item("Promoter", false),
//        Item("Proof Reader", false),
//        Item("Property Buyer", false),
//        Item("Property Dealer", false),
//        Item("Property Developer", false),
//        Item("Property Manager", false),
//        Item("Property Valuer", false),
//        Item("Proprietor", false),
//        Item("Psychiatrist", false),
//        Item("Psychoanalyst", false),
//        Item("Psychologist", false),
//        Item("Psychotherapist", false),
//        Item("Public House Manager", false),
//        Item("Public Relations Of?cer", false),
//        Item("Publican", false),
//        Item("Publicity Manager", false),
//        Item("Publisher", false),
//        Item("Publishing Manager", false),
//        Item("Purchase Clerk", false),
//        Item("Purchase Ledger Clerk", false),
//        Item("Purchasing Assistant", false),
//        Item("Purchasing Manager", false),
//        Item("Purser", false),
//        Item("Quality Controller", false),
//        Item("Quality Engineer", false),
//        Item("Quality Inspector", false),
//        Item("Quality Manager", false),
//        Item("Quality Technician", false),
//        Item("Quantity Surveyor", false),
//        Item("Quarry Worker", false),
//        Item("Racehorse Groom", false),
//        Item("Racing Organiser", false),
//        Item("Radio Controller", false),
//        Item("Radio Director", false),
//        Item("Radio Engineer", false),
//        Item("Radio Operator", false),
//        Item("Radio Presenter", false),
//        Item("Radio Producer", false),
//        Item("Radiographer", false),
//        Item("Radiologist", false),
//        Item("Rally Driver", false),
//        Item("Receptionist", false),
//        Item("Recorder", false),
//        Item("Records Supervisor", false),
//        Item("Recovery Vehicle Coordinator", false),
//        Item("Recreational", false),
//        Item("Recruitment Consultant", false),
//        Item("Rector", false),
//        Item("Reflexologist", false),
//        Item("Refractory Engineer", false),
//        Item("Refrigeration Engineer", false),
//        Item("Refuse Collector", false),
//        Item("Registrar", false),
//        Item("Regulator", false),
//        Item("Relocation Agent", false),
//        Item("Remedial Therapist", false),
//        Item("Rent Collector", false),
//        Item("Rent Offcer", false),
//        Item("Repair Man", false),
//        Item("Repairer", false),
//        Item("Reporter", false),
//        Item("Representative", false),
//        Item("Reprographic Assistant", false),
//        Item("Research Analyst", false),
//        Item("Research Consultant", false),
//        Item("Research Director", false),
//        Item("Research Scientist", false),
//        Item("Research Technician", false),
//        Item("Researcher", false),
//        Item("Resin Caster", false),
//        Item("Restaurant Manager", false),
//        Item("Restaurateur", false),
//        Item("Restorer", false),
//        Item("Retired", false),
//        Item("Revenue Clerk", false),
//        Item("Revenue Officer", false),
//        Item("Riding Instructor", false),
//        Item("Rig Worker", false),
//        Item("Rigger", false),
//        Item("Riveter", false),
//        Item("Road Safety Officer", false),
//        Item("Road Sweeper", false),
//        Item("Road Worker", false),
//        Item("Roadworker", false),
//        Item("Roof Tiler", false),
//        Item("Roofer", false),
//        Item("Rose Grower", false),
//        Item("Royal Marine", false),
//        Item("Rug Maker", false),
//        Item("Saddler", false),
//        Item("Safety Officer", false),
//        Item("Sail Maker", false),
//        Item("Sales Administrator", false),
//        Item("Sales Assistant", false),
//        Item("Sales Director", false),
//        Item("Sales Engineer", false),
//        Item("Sales Executive", false),
//        Item("Sales Manager", false),
//        Item("Sales Representative", false),
//        Item("Sales Support", false),
//        Item("Salesman", false),
//        Item("Saleswoman", false),
//        Item("Sand Blaster", false),
//        Item("Saw Miller", false),
//        Item("Scaffolder", false),
//        Item("School Crossing", false),
//        Item("School Inspector", false),
//        Item("Scientific Officer", false),
//        Item("Scientist", false),
//        Item("Scrap Dealer", false),
//        Item("Screen Printer", false),
//        Item("Screen Writer", false),
//        Item("Script Writer", false),
//        Item("Sculptor", false),
//        Item("Seaman", false),
//        Item("Seamstress", false),
//        Item("Secretary", false),
//        Item("Security Consultant", false),
//        Item("Security Controller", false),
//        Item("Security Guard", false),
//        Item("Security Officer", false),
//        Item("Servant", false),
//        Item("Service Engineer", false),
//        Item("Service Manager", false),
//        Item("Share Dealer", false),
//        Item("Sheet Metal Worker", false),
//        Item("Shelf Filler", false),
//        Item("Shelter Warden", false),
//        Item("Shepherd", false),
//        Item("Sheriff", false),
//        Item("Sheriff Clerk", false),
//        Item("Sheriff Principal", false),
//        Item("Shift Controller", false),
//        Item("Ship Broker", false),
//        Item("Ship Builder", false),
//        Item("Shipping Clerk", false),
//        Item("Shipping Officer", false),
//        Item("Shipwright", false),
//        Item("Shipyard Worker", false),
//        Item("Shoe Maker", false),
//        Item("Shoe Repairer", false),
//        Item("Shooting Instructor", false),
//        Item("Shop Assistant", false),
//        Item("Shop Fitter", false),
//        Item("Shop Keeper", false),
//        Item("Shop Manager", false),
//        Item("Shop Proprietor", false),
//        Item("Shot Blaster", false),
//        Item("Show Jumper", false),
//        Item("Showman", false),
//        Item("Shunter", false),
//        Item("Sign Maker", false),
//        Item("Signalman", false),
//        Item("Signwriter", false),
//        Item("Site Agent", false),
//        Item("Site Engineer", false),
//        Item("Skipper", false),
//        Item("Slater", false),
//        Item("Slaughterman", false),
//        Item("Smallholder", false),
//        Item("Social Worker", false),
//        Item("Software Consultant", false),
//        Item("Software Engineer", false),
//        Item("Soldier", false),
//        Item("Solicitor", false),
//        Item("Song Writer", false),
//        Item("Sound Artist", false),
//        Item("Sound Engineer", false),
//        Item("Sound Technician", false),
//        Item("Special Constable", false),
//        Item("Special Needs", false),
//        Item("Speech Therapist", false),
//        Item("Sports Administrator", false),
//        Item("Sports Coach", false),
//        Item("Sports Commentator", false),
//        Item("Sportsman", false),
//        Item("Sportsperson", false),
//        Item("Sportswoman", false),
//        Item("Spring Maker", false),
//        Item("Stable Hand", false),
//        Item("Staff Nurse", false),
//        Item("Stage Director", false),
//        Item("Stage Hand", false),
//        Item("Stage Manager", false),
//        Item("Stage Mover", false),
//        Item("Station Manager", false),
//        Item("Stationer", false),
//        Item("Statistician", false),
//        Item("Steel Erector", false),
//        Item("Steel Worker", false),
//        Item("Steeplejack", false),
//        Item("Stenographer", false),
//        Item("Steward", false),
//        Item("Stewardess", false),
//        Item("Stock Controller", false),
//        Item("Stock Manager", false),
//        Item("Stockbroker", false),
//        Item("Stockman", false),
//        Item("Stocktaker", false),
//        Item("Stone Cutter", false),
//        Item("Stone Sawyer", false),
//        Item("Stonemason", false),
//        Item("Store Detective", false),
//        Item("Storeman", false),
//        Item("Storewoman", false),
//        Item("Street Entertainer", false),
//        Item("Street Trader", false),
//        Item("Stud Hand", false),
//        Item("Student", false),
//        Item("Student Nurse", false),
//        Item("Student Teacher", false),
//        Item("Studio Manager", false),
//        Item("Sub-Postmaster", false),
//        Item("Sub-Postmistress", false),
//        Item("Supervisor", false),
//        Item("Supply Teacher", false),
//        Item("Surgeon", false),
//        Item("Surveyor", false),
//        Item("Systems Analyst", false),
//        Item("Systems Engineer", false),
//        Item("Systems Manager", false),
//        Item("TV Editor", false),
//        Item("Tachograph Analyst", false),
//        Item("Tacker", false),
//        Item("Tailor", false),
//        Item("Tank Farm Operative", false),
//        Item("Tanker Driver", false),
//        Item("Tanner", false),
//        Item("Tattooist", false),
//        Item("Tax Advisor", false),
//        Item("Tax Analyst", false),
//        Item("Tax Assistant", false),
//        Item("Tax Consultant", false),
//        Item("Tax Inspector", false),
//        Item("Tax Manager", false),
//        Item("Tax Officer", false),
//        Item("Taxi Controller", false),
//        Item("Taxi Driver", false),
//        Item("Taxidermist", false),
//        Item("Tea Blender", false),
//        Item("Tea Taster", false),
//        Item("Teacher", false),
//        Item("Teachers Assistant", false),
//        Item("Technical Advisor", false),
//        Item("Technical Analyst", false),
//        Item("Technical Assistant", false),
//        Item("Technical Author", false),
//        Item("Technical Clerk", false),
//        Item("Technical Co-ordinator", false),
//        Item("Technical Director", false),
//        Item("Technical Editor", false),
//        Item("Technical Engineer", false),
//        Item("Technical Illustrator", false),
//        Item("Technical Instructor", false),
//        Item("Technical Liaison", false),
//        Item("Technical Manager", false),
//        Item("Technician", false),
//        Item("Telecommunication", false),
//        Item("Telecommunications", false),
//        Item("Telegraphist", false),
//        Item("Telemarketeer", false),
//        Item("Telephone Engineer", false),
//        Item("Telephonist", false),
//        Item("Telesales Person", false),
//        Item("Television Director", false),
//        Item("Television Engineer", false),
//        Item("Television Presenter", false),
//        Item("Television Producer", false),
//        Item("Telex Operator", false),
//        Item("Temperature Time", false),
//        Item("Tennis Coach", false),
//        Item("Textile Consultant", false),
//        Item("Textile Engineer", false),
//        Item("Textile Technician", false),
//        Item("Textile Worker", false),
//        Item("Thatcher", false),
//        Item("Theatre Manager", false),
//        Item("Theatre Technician", false),
//        Item("Theatrical Agent", false),
//        Item("Therapist", false),
//        Item("Thermal Engineer", false),
//        Item("Thermal Insulator", false),
//        Item("Ticket Agent", false),
//        Item("Ticket Inspector", false),
//        Item("Tiler", false),
//        Item("Timber Inspector", false),
//        Item("Timber Worker", false),
//        Item("Tobacconist", false),
//        Item("Toll Collector", false),
//        Item("Tool Maker", false),
//        Item("Tour Agent", false),
//        Item("Tour Guide", false),
//        Item("Town Clerk", false),
//        Item("Town Planner", false),
//        Item("Toy Maker", false),
//        Item("Toy Trader", false),
//        Item("Track Worker", false),
//        Item("Tractor Driver", false),
//        Item("Tractor Mechanic", false),
//        Item("Trade Mark Agent", false),
//        Item("Trade Union Official", false),
//        Item("Trading Standards", false),
//        Item("Traffic Warden", false),
//        Item("Train Driver", false),
//        Item("Trainee Manager", false),
//        Item("Training Advisor", false),
//        Item("Training Assistant", false),
//        Item("Training Co-ordinator", false),
//        Item("Training Consultant", false),
//        Item("Training Instructor", false),
//        Item("Training Manager", false),
//        Item("Training Officer", false),
//        Item("Transcriber", false),
//        Item("Translator", false),
//        Item("Transport Clerk", false),
//        Item("Transport Consultant", false),
//        Item("Transport Controller", false),
//        Item("Transport Engineer", false),
//        Item("Transport Manager", false),
//        Item("Transport Officer", false),
//        Item("Transport Planner", false),
//        Item("Travel Agent", false),
//        Item("Travel Clerk", false),
//        Item("Travel Consultant", false),
//        Item("Travel Courier", false),
//        Item("Travel Guide", false),
//        Item("Travel Guide Writer", false),
//        Item("Travel Representative", false),
//        Item("Travelling Showman", false),
//        Item("Treasurer", false),
//        Item("Tree Feller", false),
//        Item("Tree Surgeon", false),
//        Item("Trichologist", false),
//        Item("Trinity House Pilot", false),
//        Item("Trout Farmer", false),
//        Item("Tug Skipper", false),
//        Item("Tunneller", false),
//        Item("Turf Accountant", false),
//        Item("Turkey Farmer", false),
//        Item("Turner", false),
//        Item("Tutor", false),
//        Item("Typesetter", false),
//        Item("Typewriter Engineer", false),
//        Item("Typist", false),
//        Item("Tyre Builder", false),
//        Item("Tyre Fitter", false),
//        Item("Tyre Inspector", false),
//        Item("Tyre Technician", false),
//        Item("Undertaker", false),
//        Item("Underwriter", false),
//        Item("Upholsterer", false),
//        Item("Valuer", false),
//        Item("Valve Technician", false),
//        Item("Van Driver", false),
//        Item("Vehicle Assessor", false),
//        Item("Vehicle Body Worker", false),
//        Item("Vehicle Engineer", false),
//        Item("Vehicle Technician", false),
//        Item("Ventriloquist", false),
//        Item("Verger", false),
//        Item("Veterinary Surgeon", false),
//        Item("Vicar", false),
//        Item("Video Artist", false),
//        Item("Violin Maker", false),
//        Item("Violinist", false),
//        Item("Voluntary Worker", false),
//        Item("Wages Clerk", false),
//        Item("Waiter", false),
//        Item("Waitress", false),
//        Item("Warden", false),
//        Item("Warehouse Manager", false),
//        Item("Warehouseman", false),
//        Item("Warehousewoman", false),
//        Item("Watchmaker", false),
//        Item("Weaver", false),
//        Item("Weighbridge Clerk", false),
//        Item("Weighbridge Operator", false),
//        Item("Welder", false),
//        Item("Welfare Assistant", false),
//        Item("Welfare Officer", false),
//        Item("Welfare Rights Officer", false),
//        Item("Wheel Clamper", false),
//        Item("Wholesale Newspaper", false),
//        Item("Window Cleaner", false),
//        Item("Window Dresser", false),
//        Item("Windscreen Fitter", false),
//        Item("Wine Merchant", false),
//        Item("Wood Carver", false),
//        Item("Wood Cutter", false),
//        Item("Wood Worker", false),
//        Item("Word Processing Operator", false),
//        Item("Works Manager", false),
//        Item("Writer", false),
//        Item("Yacht Master", false),
//        Item("Yard Manager", false),
//        Item("Youth Hostel Warden", false),
//        Item("Youth Worker", false),
//        Item("Zoo Keeper", false),
//        Item("Zoo Manager", false),
//        Item("Zoologist", false)
//    )
//
//    var searchText : String = ""
//
//    lateinit var adapter: ItemAdapter
//
//    override fun onCreate(savedInstanceState: Bundle?) {
//        super.onCreate(savedInstanceState)
//        setContentView(R.layout.activity_choose_skills)
//
//        val intentSkills = intent.getStringArrayListExtra("skills") ?: arrayListOf()
//        intentSkills.forEach {
//            val index =skill_list.indexOf(Item(it, false))
//            if(index!=-1){
//                skill_list[index].active = true
//            }
//        }
//
//        val rv = findViewById<RecyclerView>(R.id.recycleView)
//        rv.layoutManager = LinearLayoutManager(this)
//        adapter = ItemAdapter(skill_list)
//
//        adapter.checked_skills = intent.getStringArrayListExtra("skills") ?: arrayListOf()
//
//        rv.adapter = adapter
//
//        val searchView = findViewById<SearchView>(R.id.searchBar)
//
//        findViewById<SearchView>(R.id.searchBar)?.setOnQueryTextListener(object : SearchView.OnQueryTextListener {
//
//            override fun onQueryTextChange(qString: String): Boolean {
//                if (qString == "") {
//                    onQueryTextSubmit("")
//                }
//                searchText = qString
//                return true
//            }
//            override fun onQueryTextSubmit(qString: String): Boolean {
//                adapter.addFilter(qString)
//                findViewById<SearchView>(R.id.searchBar)?.clearFocus()
//                return true
//            }
//
//        })
//    }
//
//    override fun onSaveInstanceState(outState: Bundle) {
//        super.onSaveInstanceState(outState)
//        outState.putStringArrayList("skills", adapter.checked_skills as ArrayList<String>)
//        outState.putString("searchText", searchText)
//    }
//
//    override fun onRestoreInstanceState(savedInstanceState: Bundle) {
//        super.onRestoreInstanceState(savedInstanceState)
//        adapter.checked_skills = savedInstanceState.getStringArrayList("skills") ?: arrayListOf()
//        searchText = savedInstanceState.getString("searchText", "")
//        findViewById<SearchView>(R.id.searchBar)?.setQuery(searchText, true)
//        findViewById<SearchView>(R.id.searchBar)?.clearFocus()
//        populateSkills()
//    }
//
//    override fun onCreateOptionsMenu(menu: Menu): Boolean {
//        val inflater: MenuInflater = menuInflater
//        inflater.inflate(R.menu.navbar, menu)
//        supportActionBar?.title = "Choose your skills"
//        //supportActionBar?.setBackgroundDrawable(ColorDrawable(Color.parseColor("#03a2ff")))
//        menu.findItem(R.id.pencil).setVisible(false)
//        return true
//    }
//
//    override fun onBackPressed() {
//        val resultData = Intent()
//        resultData.putExtra("skills", adapter.checked_skills as ArrayList<String>)
//        setResult(Activity.RESULT_OK, resultData)
//
//        super.onBackPressed()
//    }
//
//    private fun populateSkills(){
//
//
////        skill_entry_holder?.let{
////            it.removeAllViews()
////            skill_list.forEachIndexed { index, skill ->
////                val inflater: LayoutInflater = layoutInflater
////                val skill_entry: CheckedTextView =
////                    inflater.inflate(R.layout.skills_entry, null) as CheckedTextView
////                skill_entry.text = skill
////                if(checked_skills?.indexOf(skill)!=-1){
////                    skill_entry.isChecked = true
////                }
////                else{
////                    skill_entry.isChecked = false
////                }
////
////                skill_entry.id = index
////                skill_entry.setOnClickListener {
////                    val entry = it as CheckedTextView
////                    entry.isChecked = !entry.isChecked
////                    if (entry.isChecked && checked_skills.indexOf(entry.text.toString()) == -1) {
////                        checked_skills.add(entry.text.toString())
////                    } else {
////                        checked_skills.remove(entry.text.toString())
////                    }
////                }
////                it.addView(skill_entry)
////            }
////        }
//    }
//}